#!/usr/bin/env php
<?php

declare(strict_types=1);

use Forja\Console\Kernel;

require __DIR__ . '/vendor/autoload.php';

/** @var Forja\Foundation\Application $app */
$app = require __DIR__ . '/bootstrap/app.php';

exit(new Kernel($app)->run());
