<?php

declare(strict_types=1);

namespace Forja\Database\Schema\Grammar;

use Forja\Database\Schema\ColumnDefinition;

final class PostgresSchemaGrammar extends SchemaGrammar
{
    public function compileHasTable(string $table): array
    {
        return ['select count(*) from information_schema.tables where table_schema = current_schema() and table_name = ?', [$table]];
    }

    protected function autoIncrementPrimaryKey(): string
    {
        return 'bigint generated by default as identity primary key';
    }

    protected function booleanLiteral(bool $value): string
    {
        return $value ? 'true' : 'false';
    }

    protected function type(ColumnDefinition $column): string
    {
        return match ($column->type) {
            'string' => 'varchar(' . $this->parameter($column, 'length', 255) . ')',
            'text' => 'text',
            'integer' => 'integer',
            'bigInteger' => 'bigint',
            'boolean' => 'boolean',
            'decimal' => sprintf('decimal(%d, %d)', $this->parameter($column, 'precision', 8), $this->parameter($column, 'scale', 2)),
            'float' => 'double precision',
            'date' => 'date',
            'dateTime', 'timestamp' => 'timestamp(0) without time zone',
            'json' => 'jsonb',
            'uuid' => 'uuid',
            default => $column->type,
        };
    }
}
