<?php

declare(strict_types=1);

use Forja\Database\Connection;
use Forja\Database\DatabaseConfig;
use Forja\Database\Exception\QueryException;
use Forja\Database\Schema\Blueprint;
use Forja\Database\Schema\Schema;

function blueprint(Closure $define): Blueprint
{
    $blueprint = new Blueprint('posts');
    $define($blueprint);

    return $blueprint;
}

function schemaFor(string $driver): Schema
{
    return new Schema(new Connection(new DatabaseConfig($driver)));
}

$definition = static function (Blueprint $table): void {
    $table->id();
    $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
    $table->string('title', 120);
    $table->boolean('published')->default(false);
    $table->json('meta')->nullable();
    $table->timestamps();
    $table->index('title');
};

it('gera DDL para SQLite', function () use ($definition): void {
    expect(schemaFor('sqlite')->grammar()->compileCreate(blueprint($definition)))->toBe([
        'create table "posts" ("id" integer primary key autoincrement not null, "user_id" integer not null, "title" varchar(120) not null, '
        . '"published" integer not null default 0, "meta" text null, "created_at" datetime null, "updated_at" datetime null, '
        . 'foreign key ("user_id") references "users" ("id") on delete cascade)',
        'create index "posts_title_index" on "posts" ("title")',
    ]);
});

it('gera DDL para MySQL', function () use ($definition): void {
    expect(schemaFor('mysql')->grammar()->compileCreate(blueprint($definition))[0])->toBe(
        'create table `posts` (`id` bigint unsigned not null auto_increment primary key, `user_id` bigint unsigned not null, `title` varchar(120) not null, '
        . '`published` tinyint(1) not null default 0, `meta` json null, `created_at` datetime null, `updated_at` datetime null, '
        . 'foreign key (`user_id`) references `users` (`id`) on delete cascade)',
    );
});

it('gera DDL para PostgreSQL', function () use ($definition): void {
    expect(schemaFor('pgsql')->grammar()->compileCreate(blueprint($definition))[0])->toBe(
        'create table "posts" ("id" bigint generated by default as identity primary key, "user_id" bigint not null, "title" varchar(120) not null, '
        . '"published" boolean not null default false, "meta" jsonb null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null, '
        . 'foreign key ("user_id") references "users" ("id") on delete cascade)',
    );
});

it('gera alterações de tabela por banco', function (): void {
    $alter = blueprint(function (Blueprint $table): void {
        $table->foreignId('category_id')->constrained('categories')->nullOnDelete();
        $table->dropColumn('legacy');
    });

    expect(schemaFor('sqlite')->grammar()->compileAlter($alter))->toBe([
        'alter table "posts" add column "category_id" integer null references "categories" ("id") on delete set null',
        'alter table "posts" drop column "legacy"',
    ])->and(schemaFor('mysql')->grammar()->compileAlter($alter))->toBe([
        'alter table `posts` add column `category_id` bigint unsigned null',
        'alter table `posts` drop column `legacy`',
        'alter table `posts` add constraint `posts_category_id_foreign` foreign key (`category_id`) references `categories` (`id`) on delete set null',
    ]);
});

it('cria, altera, renomeia e remove tabelas no SQLite', function (): void {
    $connection = sqlite();
    $schema = new Schema($connection);

    $schema->create('notes', function (Blueprint $table): void {
        $table->id();
        $table->string('body');
        $table->string('code')->unique();
    });
    $schema->table('notes', fn (Blueprint $table): \Forja\Database\Schema\ColumnDefinition => $table->integer('priority')->default(1));
    $connection->table('notes')->insert(['body' => 'oi', 'code' => 'a']);

    expect($schema->hasTable('notes'))->toBeTrue()
        ->and($connection->table('notes')->first())->toBe(['id' => 1, 'body' => 'oi', 'code' => 'a', 'priority' => 1])
        ->and(fn (): bool => $connection->table('notes')->insert(['body' => 'dup', 'code' => 'a']))->toThrow(QueryException::class, 'UNIQUE');

    $schema->rename('notes', 'memos');
    expect($schema->hasTable('memos'))->toBeTrue()->and($schema->hasTable('notes'))->toBeFalse();

    $schema->drop('memos');
    $schema->dropIfExists('memos');
    expect($schema->hasTable('memos'))->toBeFalse();
});

it('aplica chaves estrangeiras com cascade no SQLite', function (): void {
    $connection = sqliteWithSchema();
    $connection->table('users')->insert(['name' => 'Ada', 'email_address' => 'ada@forja.test']);
    $connection->table('posts')->insert(['user_id' => 1, 'title' => 'Post']);

    $connection->table('users')->where('id', 1)->delete();

    expect($connection->table('posts')->count())->toBe(0)
        ->and(fn (): bool => $connection->table('posts')->insert(['user_id' => 99, 'title' => 'Órfão']))->toThrow(QueryException::class, 'FOREIGN KEY');
});

it('rejeita ações de chave estrangeira e valores padrão inválidos', function (): void {
    expect(fn (): \Forja\Database\Schema\ColumnDefinition => new Blueprint('x')->foreignId('a')->constrained('b')->onDelete('explodir'))->toThrow(InvalidArgumentException::class)
        ->and(fn (): array => schemaFor('sqlite')->grammar()->compileCreate(blueprint(fn (Blueprint $t): \Forja\Database\Schema\ColumnDefinition => $t->string('a')->default([]))))->toThrow(InvalidArgumentException::class);
});
